### ISSUE TITLE
charm push reading bzr log fails if there are merge commits.

### ISSUE THREAD

**Issue by jrwren** [juju/charmstore-client#111] opened 2017-02-06 22:49 UTC
```
$ JUJU_CHARMSTORE=https://api.staging.jujucharm
s.com/charmstore charm push etcd test-m
url: cs:~evarlast/test-m-0
channel: unpublished
ERROR cannot parse bzr log: cannot parse bzr log entry: invalid revision number "21 [merge]"
------------------------------------------------------------
revno: 21 [merge]
...
```

**Comment by kwmonroe** [comment] 2017-02-07 01:37
Dupe of #90

**Closed as completed** 2017-03-03 18:40 UTC
