### ISSUE TITLE
Attempting to push a bundle without a README.md complains about missing metadata.yaml

### ISSUE THREAD

**Issue by jhobbs** [juju/charmstore-client#106] opened 2017-01-04 22:13 UTC
I tried to push a bundle with only a 'bundle.yaml' in the directory. I got this error:

> jason@inire:~/ciaas-example$ charm push . cs:~jason-hobbs/ciaas-example
ERROR open /home/jason/ciaas-example/metadata.yaml: no such file or directory

Adding a README.md made the error go away.

This is with 2.1.1-0ubuntu1

**Comment by mhilton** [comment] 2018-07-11 15:50
Closing as a duplicate of #112

**Closed as completed by mhilton** 2018-07-11 15:50 UTC
Labels: duplicate, fix-commited
